# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-14 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hexVal',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
